### ISSUE TITLE
Remove Duplicate Twitch Secret Code

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/kittr#12]
The Twitch secret for token generation has been doubled up using two variables. Just through the process of creating technical debt and bugs, I have never taken the time to sort out using just one variable.

This can be cleaned up so that we only use one environment variable name for this to be more consistent.

**Comment by alexringberg** [comment]
I don't have the ability to assign myself but I can get a pr out for this.

**Comment by anthonyshew** [comment]
You've been assigned. Do yo thang, big pupper.

**Comment by masonschafercodes** [comment]
I create a PR for this as it has been open for over a month. Everything should be cleaned up and fixed now: PR can be seen here #230
