### ISSUE TITLE
The Big Move to Mantine - Step 1

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/kittr#183]
In my infinite wisdom ( /s ), I used `styled-components` to build kittr.

We have since fallen in love with how nice it is to use [Mantine](https://mantine.dev).

The plan:
1. We're already heavily working on the migration of the backend. Therefore, the branch for this needs to be branched off of the `migration` branch. That will allow us to severely cut down on merge conflicts when we eventually put the new front-end and back-end pieces together. Checkout the `mantine` branch.

2. To start, we are going to _only_ put Mantine on the pages that DO NOT use `getStaticProps`. This is to buy time for the back-end to get done with.
3. As far as design goes, we don't want to make too many drastic changes at the moment.

With that said, the first list of to-dos is:
- [x] [This document](https://mantine.dev/theming/next/) needs to be followed to set up the provider for Mantine.
- [x] We need to verify that tRPC, Nextjs, and Mantine are playing nicely with each other once this is done. (@anthonyshew or @JacobSickels will review this PR.)

Setup todos for @JacobSickels and @anthonyshew:

- [x] #246
- [ ] Add first set of components to Storybook
- [x] Create exports for use in UI apps
- [ ] Move anything that anyone has exported from `@mantine/*` to an export from `@kittr/ui`
- [ ] #249 (Make sure kittr/ui is tree-shaken)

Once you see two check marks above, the list of pages that are available for Mantine-ing are:
 
- [ ] #242
- [ ] Contact Us Page (Waiting on components)
- [ ] Email Changed (Waiting on components)
- [ ] FAQ Page (Waiting on components) (claimed by @adamwey)
- [ ] #244

Once we have these done, we will bring these changes into the `migration` branch and continue on our journey.

Thank you to anyone who picks up and helps out with this issue!

**Comment by JacobSickels** [comment]
I'm definitely here to help on this one

**Comment by adamwey** [comment]
I'm here to help with this.

**Comment by anthonyshew** [comment]
We Radix + Tailwind now.
