### ISSUE TITLE
Create ambient types using an external dependency?

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/kittr#229]
I don't want to have to import types when I want to use them. Is there a way to make this work in a nice way?

**Comment by booleans-oss** [comment]
So you mean global types ? If so, global types are the way to go about it. It's pretty straight forward [Typescript Handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html).

I think the biggest step would be to actually delete all the types import of the repo

**Comment by anthonyshew** [comment]
It isn't straightforward.

Making them global/ambient from an external dependency was non-trivial. Couldn't get it to work through several different strategies.

Making something ambient by itself is pretty simple as seen in that doc. However, getting it to work from an external dependency that is providing the types doesn't seem to be (might not even be possible). The closest I got was using a namespace which was okay-ish - but I would love to have them simply available when I want them.

Additionally, this concern may be minimized by proper typing of the return types in my queries. That would address a lot of the spots where I have to go out of my way to type something. It already would be.

**Comment by booleans-oss** [comment]
If you want to make the dependency's types all global at once from a single line, that'll be a bit difficult. From what I've tried, you can only modify the global declaration with the types you want manually. But still, you'll need to import them one by one and put them in the declare object. It's up to you to decide if it's worth it or not.

I've created a gist in case you want to see how I do it:
<script src="https://gist.github.com/booleans-oss/6aa8bfd1600de1bb0edfb3bdec97282a.js"></script>
