### ISSUE TITLE
Mantine - About Page

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/kittr#242]
Path: /apps/web/src/pages/about.page.tsx

Current Design: https://kittr.gg/about

**Comment by anthonyshew** [comment]
Closed by #243

**Comment by JacobSickels** [comment]
@adamwey I went through the About page and replaced the container components with a shared component called `Section` that comes from the kittr/ui package. The page styles are a little different and it needs a little bit more work, but we're trying to build shared components in the ui package so other parts of the app can use them. Sorry for the little backstep here, but this page is going to need a bit more work.

New code is pushed up to the `mantine` branch

**Comment by anthonyshew** [comment]
We Radix + Tailwind now.
