### ISSUE TITLE
Mantine - Why Kittr page

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/kittr#244]
Path: /apps/web/src/pages/why-kittr/index.page.tsx

Current Design: [https://kittr.gg/why-kittr](https://kittr.gg/why-kittr)

**Comment by opti21** [comment]
I will take this sir

**Comment by anthonyshew** [comment]
You're on it!

**Comment by anthonyshew** [comment]
We Radix + Tailwind now.
