### ISSUE TITLE
Broken docs links

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/kittr#245]
A couple links in the docs got lost along the way. They don't hurt anything but it's an easy clean-up thing to do.

![image](https://user-images.githubusercontent.com/35677084/174423571-1050738f-e1e7-438c-b855-451512e698bc.png)

**Comment by code-hyker** [comment]
So should those be removed?

**Comment by anthonyshew** [comment]
Yes! I think they are simply in the header or footer somewhere as a link.

**Comment by code-hyker** [comment]
Okay !Should I delete them?

**Comment by code-hyker** [comment]
I need to be assigned then.

**Comment by anthonyshew** [comment]
You got it!
