### ISSUE TITLE
Create a Storybook (or equivalent)

### ISSUE THREAD

**Issue by anthonyshew** [kittrgg/kittr#246]
Documentation and a playground for building better components.

At this point ([e220b72](https://github.com/kittrgg/kittr/commit/e220b72e31e6f862f805d45449060d122c51329e)):
- Storybook works
- The components are being exported as the `@kittr/ui` package. However, they are not being bundled and exported properly. The only export that I got to work was [here](https://github.com/kittrgg/kittr/blob/e220b72e31e6f862f805d45449060d122c51329e/apps/web/src/pages/developers/sandbox.page.tsx#L3).

**Comment by anthonyshew** [comment]
I will fix the exports being done properly in the morning.

@JacobSickels Can you make the first few components that you think we should have so I can understand the value of Storybook better? I've never used it with any amount of seriousness.

**Comment by anthonyshew** [comment]
I've got the dist exporting the stuff that we want nice and neat so we're good there.

This is a problem that I never solved from a long time ago that held me up with doing stuff in a `ui` package.

If I use the Mantine theme provider and theme hooks _within the `ui` package_, everything works out fine. The components will pick up whatever styles I'm trying for.

But, if I try to use everything as exports from `ui`, the `useTheme` hook  doesn't work.

You can currently see this happening on `mantine` branch in `apps/web/src/pages/developers/sandbox.page.tsx`. I've got the hook _in Next_ trying to be green. But at `packages/ui/src/components/Button/index.tsx`, I'm turning it pink.

The render is pink.

This holds for anything that I try to export from `ui`. There's definitely something I'm missing here about exporting a provider and its hooks from a package - but I don't know what it is. 🤔

**Comment by anthonyshew** [comment]
I set up a little bit of a typography showcase but I'm sure it can be better.

I also put a centering wrapper into `.storybook/preview.tsx`.

I think from here, it's your flex.

**Comment by JacobSickels** [comment]
> I've got the dist exporting the stuff that we want nice and neat so we're good there.
> 
> This is a problem that I never solved from a long time ago that held me up with doing stuff in a `ui` package.
> 
> If I use the Mantine theme provider and theme hooks _within the `ui` package_, everything works out fine. The components will pick up whatever styles I'm trying for.
> 
> But, if I try to use everything as exports from `ui`, the `useTheme` hook doesn't work.
> 
> You can currently see this happening on `mantine` branch in `apps/web/src/pages/developers/sandbox.page.tsx`. I've got the hook _in Next_ trying to be green. But at `packages/ui/src/components/Button/index.tsx`, I'm turning it pink.
> 
> The render is pink.
> 
> This holds for anything that I try to export from `ui`. There's definitely something I'm missing here about exporting a provider and its hooks from a package - but I don't know what it is. 🤔

What we found regarding this issue is that we cannot pass a hex color to the Button `color` property. You can only pass the color key defined as part of your theme colors.

**Comment by anthonyshew** [comment]
What we found out is I'm dumb.
